spring:
  application:
    name: api-gateway
  messages:
    basename: i18n/messages
  profiles:
    active: dev

# cors跨域设置
custom:
  cors:
    mapping: /**
    allowCredentials: false
    allowedOrigins: "*" #允许的域，多个用逗号隔开。*允许全部的域通过。一定要用双引号，否则配置文件报错。
    #    allowedMethods: POST,GET,DELETE,PUT #这样设置，静态资源将不能跨域
    allowedMethods: "*"
    allowedHeaders: "*"
#开启重试机制
#参考：http://blog.didispace.com/spring-cloud-zuul-retry-detail/
zuul:
  SendErrorFilter: #禁用过滤器
    error:
      disable: true
  retryable: true #是否开启重试功能
  ribbon:
    eager-load: #饥饿加载
      enabled: true
  routes: #配置路由
    api-common:
      path: /common/**
      stripPrefix: true
      service-id: service-common #服务service-common
    api-b:
      path: /file/**
      stripPrefix: true
      #服务service-fileclient
      service-id: service-fileclient
  # 忽略所有的默认路由，让所有路由配置均维护在配置文件中，以达到网关启动的时候就默认初始化好各个路由转发的负载均衡对象。
  ignored-services: '*'
ribbon:
  MaxAutoRetries: 3 #同一个Server重试的次数(除去首次)
  MaxAutoRetriesNextServer: 0 #切换相同Server的次数
### 日志配置
logging:
  file: logs/api-gateway.log
  level:
    com.xrlj.apigateway: debug
