spring:
  devtools:
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#debug: true #调试模式，将会看到更多的日志信息。默认关闭
zuul:
  add-host-header: true #重定向问题
  sensitive-headers: "*" #保留所有头信息传递，解决多个服务在转发中sessionId不一致的问题，到了服务层，缺少头信息的问题。注意：每个具体的服务的sessionId还是不一样的?
